### ISSUE TITLE
Issue tracker of sprint work

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/spec#131]
I'm creating this issue for tracking progress and coordinating ongoing work:

- [x] Define Core Scope `Network`: https://github.com/microsoft/hydra-spec/issues/129, https://github.com/microsoft/hydra-spec/pull/140
- [x] Define Core Scope `Health`: https://github.com/microsoft/hydra-spec/issues/129, https://github.com/microsoft/hydra-spec/pull/133
- [X] ~Define `applicationScopes` binding with `Component` in Configuration:~ https://github.com/microsoft/hydra-spec/issues/130, https://github.com/microsoft/hydra-spec/pull/135
- [X] ~Instantiation of Application Scopes should not be bound to Application Configuration~: https://github.com/microsoft/hydra-spec/issues/144, https://github.com/microsoft/hydra-spec/pull/147
- [x] dependency story: https://github.com/microsoft/hydra-spec/issues/171
- [ ] Define Trait `ExposedEndpoint`: https://github.com/microsoft/hydra-spec/issues/128
- [ ] ~~Support Different Volume Source~~ Define Trait `VolumeMounter`: https://github.com/microsoft/hydra-spec/issues/91
- [ ] Support Component Ordering and Information Passing: https://github.com/microsoft/hydra-spec/issues/23
- [ ] Define Scope for Application Metadata: https://github.com/microsoft/hydra-spec/issues/87
- [ ] Define Stateful Workload: https://github.com/microsoft/hydra-spec/issues/97
- [x] "example-first" better tutorials for the spec: https://github.com/microsoft/hydra-spec/issues/121, https://github.com/microsoft/hydra-spec/pull/190

**Comment by hongchaodeng** [comment]
Closing since the rest should be tracked in regular release roadmap
