### ISSUE TITLE
Issue tracker of Chinese Translation for OAM spec

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#261]
Now we have volunteers working on Chinese Translation, some of sections are still available if anyone want to join us:

- [x]  1.purpose_and_goals.md @KaiwenWang
- [x]  2.overview_and_terminology.md @KaiwenWang
- [x]  3.component_model.md @pigletfly
- [x]  4.application_scopes.md @LeoLiuYan
- [x]  5.traits.md @pigletfly
- [x]  6.application_configuration.md @captainroy-hy
- [x]  7.workload_types.md @captainroy-hy
- [x]  8.practical_considerations.md @captainroy-hy
- [x]  9.design_principles.md @KaiwenWang
- [x]  ~~code-of-conduct.md~~
- [x]  ~~CONTRIBUTING.md~~
- [x]  ~~governance.md~~
- [x]  introduction.md @captainroy-hy
- [x]  ~~LICENSE~~
- [ ]  notational_convention.md
- [x] ~~OWNERS.md~~
- [x]  README.md @captainroy-hy

refs #258 #233

**Comment by KaiwenWang** [comment]
Thank for wonderflow. I will complete the 1,2 and 9th doc as soon as possible and pull request.

And There are some questions about some Terminology, like Component Schematics, Trait, Scope, etc. Do these terminology need to be translate? or we just use the English word in the zh-Hans doc directly? 

Furthermore, how to translate the terminology below?
1.  Component Schematics
2. Application scope

After all, I think the translation  of terminology  needs to be unified first.

Waiting for all of your opinitons. @wonderflow

**Comment by wonderflow** [comment]
I have setup a framework https://github.com/oam-dev/spec/pull/260.
In that PR, I translate OAM terminology like below:

Open Application Model = 开放云原生应用模型
Component Schematics = 组件
Application scope = 应用边界
Workload = 工作负载

**Comment by KaiwenWang** [comment]
Copy That. Thanks

**Comment by resouer** [comment]
The terms above lgtm.

**Comment by wonderflow** [comment]
We've discussed and decided to move all the translations PR to a separated branch `i18n`, so that we could merge these PRs faster without disrupting master during the process.

**Comment by Colstuwjx** [comment]
> Component Schematics = 组件

I think it's a partial translation for this term, and the word `Schematic` could translate to "模式/纲要" ( if it's similar to `Schema`, see the [wiki ref](https://zh.wikipedia.org/wiki/%E7%B6%B1%E8%A6%81_(%E8%B3%87%E6%96%99%E5%BA%AB)) ) or "议程/概要" ( if we keep the original meaning of `Schematic`) .

I prefer `Component Schematics = 组件纲要`.
It's just a suggestion from a dockone translator, feel free to ignore this if we think "组件" is better one :)

**Comment by wonderflow** [comment]
@Colstuwjx  welcome! Now we are working on [OAM spec v1alpha2 version](https://github.com/oam-dev/spec/tree/1.0.0-alpha2), are you interesting to join us translate to Chinese?

**Comment by Colstuwjx** [comment]
Yes, I'm willing to help :)

**Comment by cheimu** [comment]
Hi, I'm new to OAM and interested in translating it; don't know if this issue is still open since it has been six months after the last comments. : D

**Comment by resouer** [comment]
> Hi, I'm new to OAM and interested in translating it; don't know if this issue is still open since it has been six months after the last comments. : D

@cheimu This issue is not active anymore since a new version of OAM spec is under development. Please kindly move to the https://kubevela.io project to engage doc related effort.

**Comment by wonderflow** [comment]
closing as @resouer said
